# Config file for automatic testing at travis-ci.org
language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script: python setup.py test
after_script:
- sonar-scanner -Dsonar.login=$SONAR_TOKEN -X
addons:
  sonarcloud:
    organization: "ewatercycle"
cache: pip
